// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHi8ahRPlJGaL6lbc94iIVrmlmnnWHzMA',
    appId: '1:537193306223:web:e61dcee660594cfe0e159a',
    messagingSenderId: '537193306223',
    projectId: 'social-media-e5299',
    authDomain: 'social-media-e5299.firebaseapp.com',
    storageBucket: 'social-media-e5299.appspot.com',
    measurementId: 'G-D1P710N6BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbErMgYfaI7VJPRLlt_v_xHr7WrskZ2zM',
    appId: '1:537193306223:android:304dfa08c4a0cc6f0e159a',
    messagingSenderId: '537193306223',
    projectId: 'social-media-e5299',
    storageBucket: 'social-media-e5299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhMmZBAWGXSI-aGwpEwfNdFbNOeN5qYg',
    appId: '1:537193306223:ios:e4c9fead38707def0e159a',
    messagingSenderId: '537193306223',
    projectId: 'social-media-e5299',
    storageBucket: 'social-media-e5299.appspot.com',
    iosClientId: '537193306223-s14qlr11jgguupa05c780mirtra5f405.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
